### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [Roman-Statsura/Roman-Statsura.github.io#2]
1 итерация

### Добрый день!

_Отлично_:
- Полностью проходит проверку валидация почтового ящика
___

### Надо исправить:

- Не все имена из задания проходят: `Серёга`
- Проходит такой невалидный телефон: `+7(925 900-90-90`, `+7925) 900-90-90`, `+7 (925 -90-90`, `+7(925) 900--90-90`
- Проходит невалидный IP адрес: `http://22222223213212312255.255.255.255`, `http://www.255.255.255.255`
- Прходит порт из одной цифры: `http://ya.com:3` или вообще без цифр: `http://ya.com:`. А по заданию: `Порт начинается с двоеточия, за которым идут от 2 до 5 цифр.`
- Проходит невалидный URL: `http://ya` (tld обязательно), `http://ya.23` (tld из цифр не может быть)
- В REAME должна находиться ссылка на проект в github.io

---
**Важно:** после исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на *github.io*.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by Roman-Statsura** [comment]
Добрый день. Все замечания исправлены.

**Comment by mrprovoker** [comment]
2 итерация

Спасибо за правки. В качестве рекомендации рекомендую также исправить невалидный ip: `http://www.255.255.255.255`

---
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*
